### ISSUE TITLE
Lags when scrolling in resource calendar

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#114]
We noticed that scrolling over resourceCalendar was causing a big lag in our application.
When we want to show multiple synchronized screens of resource calendar, or when we extend dateRange to more than a week
the delay becoms noticeable and problematic.

As one of reasons we consider drawing lines and labels in DayViewSkin and TimeScaleViewSkin, because of huge amount of objects that are created and especially  the styles that are being added and removed back and forth.
![image](https://user-images.githubusercontent.com/68653276/97189295-b8f3e880-17a4-11eb-8337-25cf4e45f8d5.png)

What are possible solutions for this issue?

**Comment by PSI-Polska-ASM** [comment]
Hi, could you address the issue?

**Comment by dlemmermann** [comment]
No, I could not. I am swamped with work right now. But I am always open for suggestions on how to improve the performance in this region. Constantly adding and removing nodes to the JavaFX scenegraph is always causing performance issues when the number of nodes becomes too big. This is the reason why FlexGanttFX uses the Canvas API as there we always knew that we have to deal with thousands and thousands of object all the time while scrolling. CalendarFX however was designed for "normal" calendars, where the node count was expected to be in the hundreds and layout did not happen all the time. 

The resource calendar you initially requested has grown bigger and bigger and the node count has steadily increased. I think you are pushing this a little bit too far.

Nevertheless, there are usually ways to optimize things. In FlexGanttFX we started using the translate-x property to increase performance. Instead of rebuilding the view over and over again we build it once, but we build it bigger than needed for the visible area. When scrolling we use translate-x to simply "move" the main node to the left or right. While doing that no nodes are being added, or removed, and also no CSS styling is needed. Only when we reach the end of the main node do we rebuild. This is a very advanced technique and implementing it took a long time. You can see the result here: https://www.youtube.com/watch?v=xPY_J_uGjW8

So the translate property might be the key for solving this issue, but this is not something I can do "on the side". Feel free to give it a try yourself and let me know if you want to merge a pull request.

**Comment by adrianjaroszewicz** [comment]
Hello Dirk,
it looks like we're forced to come back to this issue. We would like to go a direction that you have suggested - so we would like to give it a try and introduce the translate-x property mechanism in CalendarFX ourselves. Would you still be interested in merging such an improvement in CalendarFX in case of a successful implementation? I assume that yes, but half a year has passed so I thought it is better to ask before starting the investigation :) Our idea is to introduce it as an experimental feature - so that it could be easily turned off/on (by a property) - and be properly tested before becoming a core mechanism. What do you think about that?
All the best,
Adrian

**Comment by dlemmermann** [comment]
Feel free to give it a try. But obviously I can not guarantee you that I will merge it. I will need to see the result first. However, it is totally OK if you simply stay on your own fork or create a new project and copy everything over. You do not have to stay with the main branch of CalendarFX at all. The CalendarFX license allows you all of that.

Dirk
