### ISSUE TITLE
[11.5.0] Remove snapshot dependency on controlsfx 9.0.1-SNAPSHOT once released

### ISSUE THREAD

**Issue by jotomo** [dlemmermann/CalendarFX#41]
Release 11.5.0 uses controlsfx in version _9.0.1-SNAPSHOT_, requiring a consumer of CalendarFX to enable the Sonatype snapshot repo, with the known drawbacks.
https://github.com/dlemmermann/CalendarFX/blob/master-11/CalendarFXView/pom.xml#L70

**Comment by dlemmermann** [comment]
The first release of ControlsFX for JavaFX 11 is coming very soon. Then I will make this change.

**Comment by dlemmermann** [comment]
The dependencies have been updated to use a production release of ControlsFX (11.0.0).

**Comment by kr5ture** [comment]
@dlemmermann Are there any plans to release these changes to `maven` repository anytime soon?

**Comment by dlemmermann** [comment]
Working on it. That's why the ownership of this repo was just moved from dlemmermann/ to dlsc-software-consulting-gmbh. We are in the process of adding CI / CD all the way from GitHub to bintray and Maven central. Currently I can't say exactly when this will be done but hopefully some time next week.

**Comment by kr5ture** [comment]
Glad to hear it. Most important is that it won't be abandoned. Thanks!

**Comment by Oumar224** [comment]
teste
