### ISSUE TITLE
Most of DateControl properties do not work when using ResourceCalendarView

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#77]
There are some properties inherited from DateControl that are no longer relevant in ResourceCalendarView (like for example com.calendarfx.view.DateControl#setLayout - as far as I understand this view is not intended to show swimlanes at all). But unfortunately there are properties that are relevant to this view and do not work. I have tried with e.g. com.calendarfx.view.DateControl#setRequestedTime, com.calendarfx.view.DateControl#setStartTime, com.calendarfx.view.DateControl#setEndTime and none of these methods work (they do not affect the view).

But one thing is fixing and the other is the visibility of these properties. Is it possible to hide these not-relevant ones? Or could you please provide a list of properties that are relevant so that I could expose only these that affect the view to the end-user?

**Comment by dlemmermann** [comment]
It is not possible to hide them because all controls inherit from DateControl and more specifically from DayViewBase. So instead of telling you which properties work and which do not, just tell me (in individual tickets) what it is you are trying to accomplish and I will either tell you how to do that or I will make sure that you can do it, if it is not supported, yet.

The start / end / requested time really do not make sense for the ResourceCalendarView as everything can now be controlled via the scrollTimeProperty. If for example you want to limit the view to an "earliest" time to which the user can scroll then simply listen to the scrollTimeProperty and reject setting it to a time that is before the earliest time. 

If you want the view to show a specific time (requested time) then also simply set that time on the scrollTimeProperty.

**Comment by dlemmermann** [comment]
The layout property (swimlane) should still work though.

**Comment by dlemmermann** [comment]
I just verified that the layout property works properly. :-)

**Comment by adrianjaroszewicz** [comment]
Thanks for quick responses!

> So instead of telling you which properties work and which do not, just tell me (in individual tickets) what it is you are trying to accomplish and I will either tell you how to do that or I will make sure that you can do it, if it is not supported, yet.

That's a good idea, we'll check what we really need and will let you know in separate tickets.

> I just verified that the layout property works properly. :-)

Oh, sorry, I have checked it only in my environment where I have just one calendar assigned to each resource - and probably because of that I couldn't see any results.
