### ISSUE TITLE
Having issues with repeated requests due to CalendarEvent.ENTRY_CHANGED.

### ISSUE THREAD

**Issue by BowMonk** [dlemmermann/CalendarFX#84]
Hello, i'm trying to use CalendarFX with a database and I have my functions set up and ready to go. However, i'm running into an issue with the title change. Because of how my event handler is built, requests are sent to the server-side from client-side to update an entry every time that even a letter of the title of an entry changes, I was wondering if I could get some tips on how to get around that. Maybe some wrapper of some sort or usage of my current handler with other tools that I haven't thought about yet. Any advice/tip would be appreciated.

Thanks in advance.

**Comment by dlemmermann** [comment]
I think you should delay those updates. What I always use in these situations is the Service API of the javafx concurrency package. A service runs a task in a separate thread. The good thing about a service is that you can call "restart" every time a property changes. Inside the task you put in a delay, so that the task does not run right away. This way the task will only run once the delay has passed without you calling "restart". This is the same approach the search uses inside CalendarFX. When the user enters a search text inside the search text field I keep resetting the service that performs the actual search. Only when the user has paused long enough between two keystrokes the search will happen.

**Comment by dlemmermann** [comment]
Advise was given, closing the ticket.
