### ISSUE TITLE
Display of date in TimeScaleView when using infinite scrolling

### ISSUE THREAD

**Issue by jbalcerzak** [dlemmermann/CalendarFX#95]
On date change we would like to display it on the side of frame.
![resourceCalendar_how_add_date2](https://user-images.githubusercontent.com/65945003/82888576-c7b24700-9f49-11ea-8fda-3400ada20fa1.png)

**Comment by dlemmermann** [comment]
This should be added directly to the TimeScaleView.

**Comment by dlemmermann** [comment]
Or if you like you could copy / paste TimeScaleView and create something called a DateScaleView.

**Comment by jbalcerzak** [comment]
If you were asked to implemented such feature, how it could look like, what are the options?

**Comment by dlemmermann** [comment]
Not much magic I guess. Just labels with the date scrolling up and down. So while there are many labels for the times, there will be only a few for the dates. I think I would want to add the date labels to the TimeScaleView. So instead of showing 00:00 for midnight that label would show the date but with a different styling. .....

**Comment by dlemmermann** [comment]
Status?

**Comment by dlemmermann** [comment]
I have changed the code so that the midnight time "00:00" will not be displayed but instead the user will see the date of the day starting. The formatting of the date and of the times can be controlled by two formatter properties on TimeScaleView.

<img width="1143" alt="Bildschirmfoto 2020-08-19 um 14 42 58" src="https://user-images.githubusercontent.com/9534301/90636070-5c1b0580-e22a-11ea-8228-f4e1d52fc362.png">
